# copy this to config.yaml and override anything you need

github:
  token: "abcdefgh"  # https://github.com/settings/tokens
  assignee_login: "TicClick"
  repo: "someone/osu-wiki"
  title_regex: ^\[(\w+.?)?RU(.+)?\]

discord:
  token: "abc.def.ghi"  # bot token from https://discord.com/developers/applications
  owner_id: 12345
  review_channel: 67890
  review_role_id: 12345

storage:
  path: "runtime/osuwiki.db"

debug: False

logging:
  file: "runtime/librarian.log"
  level: DEBUG