# copy this to config.yaml and override anything you need

github:
  token: "abcdefgh"  # https://github.com/settings/tokens
  assignee_login: null
  repo: "ppy/osu-wiki"

discord:
  token: "abc.def.ghi"  # bot token from https://discord.com/developers/applications
  review_channel: 67890
  review_role_id: 12345
  language_code: "ru"
  store_in_pins: true

runtime:
  dir: /home/username/discord-bot/runtime

storage:
  path: "{runtime}/osuwiki.db"

logging:
  file: "{runtime}/librarian.log"
  level: DEBUG
