# This is a basic workflow to help you get started with Actions

name: Deploy Librarian

# Controls when the action will run. 
on:
  push:
    branches:
      - add-deploy-workflow
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: setup ssh
        shell: bash
        run: |
          echo 'read SECRET; echo "$SECRET"' > ~/echo.sh && chmod +x ~/echo.sh

          mkdir -p ~/.ssh
          sudo chmod 0700 ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          sudo chmod 0600 ~/.ssh/id_rsa

          ssh-keyscan -H ${{secrets.DEPLOY_HOSTNAME}} > ~/.ssh/known_hosts
      - name: checkout and run
        shell: bash
        env:
          REPOSITORY: https://github.com/TicClick/librarian.git
          WHERE: ${{secrets.DEPLOY_SERVER_AND_USER}}
          PASS: ${{secrets.SSH_PASSPHRASE}}
        run: |
          ssh -o LogLevel=ERROR -i ~/.ssh/id_rsa "$WHERE" "[ -e librarian ] || git clone $REPOSITORY"
          eval $( SSH_ASKPASS=~/echo.sh $SSSH "cd librarian && git fetch && git checkout tags/v1.3" )
          eval $( SSH_ASKPASS=~/echo.sh $SSSH "pkill -INT -f librarian.main && tmux kill-session -t librarian" <<< "$PASS" )
          eval $( SSH_ASKPASS=~/echo.sh $SSSH "cd librarian && make setup && tmux new -d -s librarian 'make run'" <<< "$PASS" )
