# This is a basic workflow to help you get started with Actions

name: Push

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: setup ssh
        run: |
          echo 'read SECRET; echo "$SECRET"' >> ~/echo.sh && chmod +x ~/echo.sh

          mkdir -p ~/.ssh
          echo ${{secrets.SSH_PRIVATE_KEY}} > ~/.ssh/id_rsa
          sudo chmod 0600 ~/.ssh/id_rsa

          ssh-keyscan -H ${{secrets.DEPLOY_SERVER}} > ~/.ssh/known_hosts
          SSH_ASKPASS=~/echo.sh ssh-add ~/.ssh/id_rsa <<< ${{secrets.SSH_PASSPHRASE}}

      - name: test stuff
        run: |
          ssh ${{secrets.DEPLOY_SERVER}} "pwd"
